name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  NAME: 'Allay-in-a-Bottle'
  MODRINTH_ID: '7IGV0Frg'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install mc-build
        run: npm i -g mc-build
      - name: Run mc-build
        run: cd datapack && mcb -build

      - name: Squash datapack
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: v0.4.0
          artifact_name: datapack-raw
          options: |
            pack_directory = "datapack"
            output_file_path = "${{ env.NAME }}.zip"
      - name: Add secondary files to datapack
        run: zip -u ${{ env.NAME }} LICENSE.txt README.md CHANGELOG.md

      - name: Squash resourcepack
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: v0.4.0
          artifact_name: resourcepack-raw
          options: |
            pack_directory = "resourcepack"
            output_file_path = "${{ env.NAME }}-Resourcepack.zip"
      - name: Add secondary files to resourcepack
        run: zip -u ${{ env.NAME }}-Resourcepack LICENSE.txt README.md CHANGELOG.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            CHANGELOG.md
            ${{ env.NAME }}.zip
            ${{ env.NAME }}-Resourcepack.zip

  release-github:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.NAME }} ${{github.ref_name}}
          body_path: CHANGELOG.md
          files: |
            ${{ env.NAME }}.zip
            ${{ env.NAME }}-Resourcepack.zip

  release-modrinth:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Publish on Modrinth
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: ${{ env.NAME }} ${{github.ref_name}}
          files-primary: ${{ env.NAME }}.zip
          files-secondary: ${{ env.NAME }}-Resourcepack.zip
          version: ${{github.ref_name}}
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: datapack
          game-versions: |
            1.20.1
